name: Generate Action Code
description: Generates the action code

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        check-latest: true
        cache: 'npm'
    - name: Generate action code
      shell: bash
      run: npm run deploy
